package de.kordondev.attendee.exception

object ErrorConstants {
    const val VALIDATION_ERROR = "VALIDATION_ERROR"
    const val UNIQUE_ERROR = "UNIQUE_ERROR"
    const val END_OF_REGISTRATION_ERROR = "END_OF_REGISTRATION_ERROR"
    const val BAD_REQUEST_ERROR = "BAD_REQUEST_ERROR"
    const val ACCESS_DENIED_ERROR = "ACCESS_DENIED_ERROR"
    const val RESOURCE_ALREADY_EXISTS_ERROR = "RESOURCE_ALREADY_EXISTS_ERROR"
    const val EXISTING_DEPENDENCY_ERROR = "EXISTING_DEPENDENCY_ERROR"
    const val NOT_FOUND_ERROR = "NOT_FOUND_ERROR"
}