version: '3.6'

services:
  database:
    image: "mysql"
    container_name: lm-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=attendee
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=secRET
    expose:
      - '3306'
  backend:
    image: "kordondev/lager-melder"
    container_name: lm-backend
    ports:
      - "8080:8080"
    depends_on:
      - "database"
  frontend:
    image: "node:lts-alpine"
    container_name: lm-frontend
    ports:
      - "8081:9000"
    volumes:
      - "../../frontend/:/app/:rw"
    command: sh -c "cd /app && yarn install && yarn serve"
