version: "3.6"

services:
  database:
    image: "mysql:9.0.1"
    container_name: lm-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=lager_melder
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=secRET
    expose:
      - "3306"
  backend:
    image: "openjdk:21"
    container_name: lm-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://lm-mysql:3306/lager_melder
    depends_on:
      - "database"
    volumes:
      - "..:/app/:rw"
    command: sh -c "cd /app && ./mvnw clean install -DskipTests && ./mvnw spring-boot:run"
  # frontend:
  #   image: "node:lts-alpine"
  #   container_name: lm-frontend
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - "../../frontend/:/app/:rw"
  #   command: sh -c "cd /app && npm install && npm run start"
