version: "3.6"

services:
  database:
    image: "postgres:18"
    container_name: lm-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lager_melder
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    expose:
      - "5432"
  backend:
    image: "openjdk:25"
    container_name: lm-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://lm-postgres:5432/lager_melder
      - JAVA_TOOL_OPTIONS="-XX:UseSVE=0"
    depends_on:
      - "database"
    volumes:
      - "..:/app/:rw"
    command: sh -c "cd /app && ./gradlew bootRun"
  # frontend:
  #   image: "node:lts-alpine"
  #   container_name: lm-frontend
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - "../../frontend/:/app/:rw"
  #   command: sh -c "cd /app && npm install && npm run start"
