version: '3.6'

services:
  database:
    image: "mysql:9.0.1"
    container_name: lm-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=lager_melder
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=secRET
    expose:
      - '3306'
