spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/attendee
    username: user
    password: pass


  mail:
    port: 25
    debug: false
    from: test@spam.com
    host: h
    username: u
    password: p

server:
  error:
    include-message: always
    include-binding-errors: always

application:
  mail:
    send: false
  admin:
    password: password
  corsOrigins: http://localhost:9000, http://lagermelder.kordondev.de
