spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/lager_melder
    username: user
    password: pass
  liquibase:
    change-log: classpath:db/changelog-master.xml
    contexts: dev

  mail:
    port: 25
    debug: false
    from: test@spam.com
    host: h
    username: u
    password: p

management:
  health:
    mail:
      enabled: false
server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api

application:
  mail:
    send: false
  admin:
    passwordHash: $2a$12$3B.Ct9RY4FxjO/qrHZGe4uHN1IsGnh.cezLNcbE8/K0eXDHoGK59q
  corsOrigins: http://localhost:9000, http://lagermelder.kordondev.de
