spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/lager_melder
  liquibase:
    change-log: classpath:db/changelog-main.xml
    contexts: prod

  mail:
    port: 25
    debug: false
    from: test@spam.com

management:
  health:
    mail:
      enabled: true

server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api

application:
  mail:
    send: true
  corsOrigins: http://localhost:9000
