spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/lager_melder
  liquibase:
    change-log: classpath:db/changelog-main.xml

  mail:
    port: 25
    debug: false
    from: test@spam.com
    host: h
    username: u
    password: p

server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api
