name: Build and publish
on:
  push:
    branches: [main]
    tags: [deploy]
  pull_request:

jobs:
  build-and-push-backend:
    name: Backend - Build, containerize and push
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "21"
          cache: "maven"
      - name: Install dependencies
        run: mvn install
        working-directory: ./backend
      - name: Execute Tests
        run: mvn test
        working-directory: ./backend
      - name: Build java
        run: mvn compile
        working-directory: ./backend
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
        id: extract_branch
        working-directory: ./backend
      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/tags/deploy' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy
        run: mvn jib:build -Djib.to.tags=${{ steps.extract_branch.outputs.branch }}-${{ github.run_id }}
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/tags/deploy' }}
        working-directory: ./backend

  build-and-push-frontend:
    name: Frontend - Build, containerize and push
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend
      - name: Run build
        run: npm run build
        working-directory: ./frontend
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
        id: extract_branch
        working-directory: ./backend
      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/tags/deploy' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/tags/deploy' }}
        with:
          push: true
          tags: kordondev/lager-melder-frontend:${{ steps.extract_branch.outputs.branch }}-${{ github.run_id }}
          file: ./frontend/Dockerfile
          context: ./frontend
