name: Build and publish
on:
  push:
    branches:
      - "*"
    tags: 
      - "*"

jobs:
  build-and-push-backend:
    name: Backend - Build, containerize and push
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "21"
          cache: "maven"
      - name: Install dependencies
        run: mvn install
        working-directory: ./backend
      - name: Execute Tests
        run: mvn test
        working-directory: ./backend
      - name: Build java
        run: mvn compile
        working-directory: ./backend
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}
      - name: Set Tag as Environment Variable
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/')
        run: mvn jib:build -Djib.to.tags=ghcr.io/${{ github.repository_owner }}/lager-melder-backend:${{ env.TAG_NAME }},ghcr.io/${{ github.repository_owner }}/lager-melder-backend:latest
        working-directory: ./backend

  build-and-push-frontend:
    name: Frontend - Build, containerize and push
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend
      - name: Run build
        run: npm run build
        working-directory: ./frontend
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          context: ./frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/lager-melder-backend:${{ env.TAG_NAME }}
            ghcr.io/${{ github.repository_owner }}/lager-melder-backend:latest
